spring:
  data:
    mongodb:
      host: localhost
      database: petstore
  application:
    name: ps-user
server:
  servlet:
    context-path: /ps-user
  port: 10001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true
